import Head from 'next/head';
import Header from '../components/Header';
import Nav from '../components/Nav';
import Results from '../components/Results';
import styles from '../styles/Home.module.css';
import requests from '../utils/requests';
import AdBanner from '../components/AdBanner';

export default function Home({ results }) {
  //console.log(results)
  return (
    <div className={styles.container}>
      <Head>
        <title>HotMovieList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      {/* Header */}
      <Header />

      {/* Nav */}
      <Nav />

      {/* Results */}
      <Results results={results} />
      <AdBanner slot="1111111111" />
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`
  ).then(res => res.json());

  return {
    props: {
      results: request,
      revalidate: 1
    }
    
  }
}
